import {test,expect} from '@playwright/test';
test('scene loads, controls work, credits and sound respond',async({page},info)=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.goto('./');await expect(page.locator('#enter')).toBeEnabled();await expect(page.locator('#error')).toBeHidden();
 await expect(page.locator('#world')).toHaveAttribute('data-actors','6');await expect(page.locator('#world')).toHaveAttribute('data-animated','6');
 await page.screenshot({path:`test-results/${info.project.name}-title.png`});
 await page.locator('#enter').click();await page.locator('#skip').click();await expect(page.locator('body')).toHaveClass(/entered/);await expect(page.locator('body')).not.toHaveClass(/intro/);
 await page.screenshot({path:`test-results/${info.project.name}-scene.png`});
 await page.locator('#sound').click();await expect(page.locator('#sound')).toHaveAttribute('aria-pressed','true');await page.locator('#sound').click();await expect(page.locator('#sound')).toHaveAttribute('aria-pressed','false');
 await page.locator('#settings').click();await page.locator('#quality').selectOption('Low');await expect(page.locator('#world')).toHaveAttribute('data-quality','Low');await page.locator('#reset').click();
 await page.locator('#about').click();await expect(page.locator('#credits')).toContainText('Amir Saeid Dehghan');await expect(page.locator('#credits')).toContainText('not affiliated');await page.getByRole('button',{name:'Close credits'}).click();
 if(info.project.name==='mobile'){await expect(page.locator('#joystick')).toBeVisible();const b=await page.locator('#joystick').boundingBox();expect(b.x).toBeGreaterThanOrEqual(0);const before=await page.locator('#world').getAttribute('data-camera');await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2,b.y+10);try{await expect(page.locator('#world')).not.toHaveAttribute('data-camera',before);}finally{await page.mouse.up();}}else{await page.locator('#world').click({position:{x:384,y:445}});await expect(page.locator('#label-title')).toHaveText('Leon S. Kennedy');await page.locator('#label-close').click();const before=await page.locator('#world').getAttribute('data-camera');await page.locator('#world').focus();await page.keyboard.down('KeyW');try{await expect(page.locator('#world')).not.toHaveAttribute('data-camera',before);}finally{await page.keyboard.up('KeyW');}}
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 expect(errors).toEqual([]);
});
test('missing model does not trap loading',async({page})=>{await page.route('**/assets/models/investigator.glb',route=>route.fulfill({status:404,body:'missing'}));await page.goto('./');await expect(page.locator('#enter')).toBeEnabled();await expect(page.locator('#load-status')).toContainText('unavailable');await expect(page.locator('#error')).toBeHidden();});
test('unsupported WebGL has a clear fallback',async({page})=>{await page.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return /webgl/i.test(type)?null:original.call(this,type,...args);};});await page.goto('./');await expect(page.locator('#error')).toBeVisible();await expect(page.locator('#error-message')).toContainText('WebGL');});
