import * as T from 'three';
export function controls(camera,canvas,colliders,audio){const keys=new Set(),touch=matchMedia('(pointer:coarse)').matches,joy=document.getElementById('joystick');document.body.classList.toggle('touch',touch);let enabled=false,drag=null,yaw=0,pitch=0,jx=0,jy=0,lastStep=0,travel=0;const euler=new T.Euler(0,0,0,'YXZ');
 const sync=()=>{euler.setFromQuaternion(camera.quaternion,'YXZ');yaw=euler.y;pitch=euler.x;};
 addEventListener('keydown',e=>{if(document.querySelector('dialog[open]'))return;if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','ShiftLeft','ShiftRight'].includes(e.code)){keys.add(e.code);e.preventDefault();}});addEventListener('keyup',e=>keys.delete(e.code));const clear=()=>{keys.clear();jx=jy=0;drag=null;};addEventListener('blur',clear);document.addEventListener('visibilitychange',clear);
 canvas.addEventListener('pointerdown',e=>{if(!enabled||document.pointerLockElement)return;canvas.focus();drag={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!enabled)return;let dx=0,dy=0;if(document.pointerLockElement===canvas){dx=e.movementX;dy=e.movementY;}else if(drag&&drag.id===e.pointerId){dx=e.clientX-drag.x;dy=e.clientY-drag.y;drag.x=e.clientX;drag.y=e.clientY;}else return;yaw-=dx*.0026;pitch=T.MathUtils.clamp(pitch-dy*.0024,-1.15,1.15);camera.quaternion.setFromEuler(euler.set(pitch,yaw,0));});canvas.addEventListener('pointerup',()=>drag=null);canvas.addEventListener('pointercancel',()=>drag=null);
 let joyPointer=null;joy.addEventListener('pointerdown',e=>{joyPointer=e.pointerId;joy.setPointerCapture(e.pointerId);moveJoy(e);});function moveJoy(e){if(e.pointerId!==joyPointer)return;const b=joy.getBoundingClientRect();jx=T.MathUtils.clamp((e.clientX-b.left-52)/38,-1,1);jy=T.MathUtils.clamp((e.clientY-b.top-52)/38,-1,1);joy.firstElementChild.style.transform=`translate(${jx*30}px,${jy*30}px)`;}joy.addEventListener('pointermove',moveJoy);const stopJoy=()=>{jx=jy=0;joyPointer=null;joy.firstElementChild.style.transform='';};joy.addEventListener('pointerup',stopJoy);joy.addEventListener('pointercancel',stopJoy);
 document.getElementById('lock').onclick=async()=>{if(!enabled)return;try{await canvas.requestPointerLock();}catch{document.getElementById('hint').textContent='Mouse capture unavailable. Drag to look; WASD to move.';}};
 const can=(x,z)=>x>-6&&x<6&&z>-42&&z<12&&!colliders.some(b=>x>b.minX&&x<b.maxX&&z>b.minZ&&z<b.maxZ);
 return{touch,sync,setEnabled(v){enabled=v;joy.hidden=!v||!touch;sync();if(!v){clear();document.exitPointerLock?.();}},update(dt,t){if(!enabled||document.querySelector('dialog[open]'))return;let x=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+jx,z=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0)+jy;const n=Math.hypot(x,z);if(n>.05){x/=Math.max(1,n);z/=Math.max(1,n);const speed=(keys.has('ShiftLeft')||keys.has('ShiftRight')?4.2:2.1)*dt,dx=(Math.cos(yaw)*x+Math.sin(yaw)*z)*speed,dz=(-Math.sin(yaw)*x+Math.cos(yaw)*z)*speed;if(can(camera.position.x+dx,camera.position.z))camera.position.x+=dx;if(can(camera.position.x,camera.position.z+dz))camera.position.z+=dz;travel+=dt;camera.position.y=1.68+Math.sin(travel*10)*.018;if(t-lastStep>.55){audio.footstep();lastStep=t;}}}};
}
